CreateThread(function()
    local blip = AddBlipForCoord(Config.blip.coords.x, Config.blip.coords.y, Config.blip.coords.z)
    SetBlipSprite(blip, Config.blip.sprite)
    SetBlipDisplay(blip, Config.blip.display)
    SetBlipScale(blip, Config.blip.scale)
    SetBlipColour(blip, Config.blip.color)
    SetBlipAsShortRange(blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString(Config.blip.label)
    EndTextCommandSetBlipName(blip)
end)